nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "fork-ts-checker-webpack-plugin@*":
    dependencies:
      "typescript": "*"
      "webpack": "*"

  "@mdx-js/react@*":
    dependencies:
      "react": "*"

  "@storybook/addon-measure@*":
    dependencies:
      "@storybook/components": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"

  "@storybook/core-client@*":
    dependencies:
      "webpack": "*"

  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"

  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"

  "eslint-config-airbnb-base@*":
    dependencies:
      "eslint": "*"
      "eslint-plugin-import": "*"

  "babel-loader@*":
    dependencies:
      "webpack": "*"

  "css-loader@*":
    dependencies:
      "webpack": "*"

  "sass-loader@*":
    dependencies:
      "webpack": "*"

  "style-loader@*":
    dependencies:
      "webpack": "*"
